Update.
Signed-off-by: andreidanila1 <andrei.danila@analog.com>

diff --git a/.github/workflows/appimage-arm64.yml b/.github/workflows/appimage-arm64.yml
--- a/.github/workflows/appimage-arm64.yml
+++ b/.github/workflows/appimage-arm64.yml
@@ -35,34 +35,32 @@ jobs:
         run: echo "REPO_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV
 
       - name: Create Scopy AppImage
-          shell: bash
-          run: |
-                echo 'ls $GITHUB_WORKSPACE'
-                ls $GITHUB_WORKSPACE
-                echo 'ls $GITHUB_WORKSPACE/scopy'
-                ls $GITHUB_WORKSPACE/scopy
-                echo 'ls $GITHUB_WORKSPACE/scopy'
-                ls $GITHUB_WORKSPACE/scopy
-                echo 'ls $GITHUB_WORKSPACE/package'
-                ls $GITHUB_WORKSPACE/package
-
-                mkdir -p $GITHUB_WORKSPACE/scopy/$REPO_NAME 
-                cp -r $GITHUB_WORKSPACE/package/* $GITHUB_WORKSPACE/scopy/packages/$REPO_NAME/
-                
-                cd $GITHUB_WORKSPACE/scopy
-                sudo apt update
-                ./ci/arm/create_sysroot.sh arm64  install_packages
-                ./ci/arm/arm_build_process.sh arm64 generate_ci_envs
-
-                docker run \
-                        --mount type=bind,source="$GITHUB_WORKSPACE/scopy",target=/home/runner/scopy \
-                        --env-file $GITHUB_WORKSPACE/scopy/ci/general/gh-actions.envs \
-                        cristianbindea/scopy2-arm64-appimage:latest \
-                        /bin/bash -c    'cd $HOME && \
-                                        sudo chown -R runner:runner scopy && \
-                                        cd $HOME/scopy && \
-                                        ./ci/arm/arm_build_process.sh arm64 install_packages move_tools move_sysroot build_scopy
-                                        mv $PWD/build/packages/$REPO_NAME $GITHUB_WORKSPACE || echo "Package directory not found!"'
+        shell: bash
+        run: |
+              echo 'ls $GITHUB_WORKSPACE'
+              ls $GITHUB_WORKSPACE
+              echo 'ls $GITHUB_WORKSPACE/scopy'
+              ls $GITHUB_WORKSPACE/scopy
+              echo 'ls $GITHUB_WORKSPACE/scopy'
+              ls $GITHUB_WORKSPACE/scopy
+              echo 'ls $GITHUB_WORKSPACE/package'
+              ls $GITHUB_WORKSPACE/package
+              mkdir -p $GITHUB_WORKSPACE/scopy/$REPO_NAME 
+              cp -r $GITHUB_WORKSPACE/package/* $GITHUB_WORKSPACE/scopy/packages/$REPO_NAME/
+              
+              cd $GITHUB_WORKSPACE/scopy
+              sudo apt update
+              ./ci/arm/create_sysroot.sh arm64  install_packages
+              ./ci/arm/arm_build_process.sh arm64 generate_ci_envs
+              docker run \
+                      --mount type=bind,source="$GITHUB_WORKSPACE/scopy",target=/home/runner/scopy \
+                      --env-file $GITHUB_WORKSPACE/scopy/ci/general/gh-actions.envs \
+                      cristianbindea/scopy2-arm64-appimage:latest \
+                      /bin/bash -c    'cd $HOME && \
+                                      sudo chown -R runner:runner scopy && \
+                                      cd $HOME/scopy && \
+                                      ./ci/arm/arm_build_process.sh arm64 install_packages move_tools move_sysroot build_scopy
+                                      mv $PWD/build/packages/$REPO_NAME $GITHUB_WORKSPACE || echo "Package directory not found!"'
 
       - name: Set short git commit SHA
         shell: bash
